### ISSUE TITLE
Dialog - Customize - CSS overflow Property ?

### ISSUE THREAD

**Issue by HanojHanu** [dxc-technology/halstack-react#1237]
**Describe the bug**
in Dialog component - if use any select component if that list is great then 10 items

![image](https://user-images.githubusercontent.com/53425981/184087280-8fe4ffc5-9afc-4531-a4ed-fbdb6de2ca6c.png)

- - -
**To Reproduce**
Take a Dialog component and add it inside the select element with a list of items 20 - 30 in select-list.

Example:

1. Create a new React App using `create-react-app`
2. Install the `@dxc-technology\halstack-react` dependencies and run the app
3. Click on ' Select component '
4. Scroll down - happening for both ' select ' & 'dialog'

**Expected behavior**
If Dialog has custom CSS property for 'overflow'
![image](https://user-images.githubusercontent.com/53425981/184089813-a7945668-e092-4484-8c70-12c95df86913.png)

**Screenshots**
Added both Screenshots in above

**Comment by GomezIvann** [comment]
Hi @HanojHanu! This seems to be an [old issue](https://github.com/dxc-technology/halstack-react/issues/1115) that was fixed in the [latest release](https://github.com/dxc-technology/halstack-react/releases/tag/6.0.0). Reproducing your bug with the latest version works fine:

![image](https://user-images.githubusercontent.com/44321109/184095106-5f802cc1-327f-49ac-ab32-84505cc3ff31.png)

Also, the Select's Listbox now has collision and other features, so it may be worth checking it! I hope it will work for your case.

**Comment by HanojHanu** [comment]
Yeah, Thank @GomezIvann 

Worked for me in the latest version 6.0.0
