### ISSUE TITLE
Review opinionated theme for all components

### ISSUE THREAD

**Issue by raquelarrojo** [dxc-technology/halstack-react#1364]
**Describe the bug**
Default theme is not correct in several components. Also, some components do not have default theme and it should be included.

**To Reproduce**
Default theme can be checked for all components using ux config.

**Expected behaviour**
Default theme should be corrected for all the components, following the guidelines. Also, some of the new components should have default theme too.

**Comment by Lisa159** [comment]
Review:

- [ ] **Quick Nav**: Default theme inputs are not documented in the website. We should add them in the [themes page](https://developer.dxc.com/halstack/next/principles/themes/).
Also, token `selectedFontColor` is not used in the component. We should remove it from HalstackContext.
![image](https://user-images.githubusercontent.com/34685461/201926136-e6d4a693-c22f-4d92-9bcc-a759e02ebd47.png)


- [ ] **Select**: Fix default theme inputs in the documentation. We should add the default theme input `optionFontColor` for the token `listOptionFontColor` and remove `listOptionFontColor` from the theme input `fontColor`.

- [ ] **Slider**: When using default theme, `totalLineColor` is getting two opacities at the same time:
![image](https://user-images.githubusercontent.com/34685461/201918737-00a75c8b-822b-4715-9723-4b25f0aac347.png)

First one (value 57) is from HalstackContext:
![image](https://user-images.githubusercontent.com/34685461/201919105-c09f90a2-e4ff-41b3-ace7-a7322b94ceed.png)

And the second one (value 61) is from the own component:
![image](https://user-images.githubusercontent.com/34685461/201918947-58c5d72c-0dd9-43f1-a38c-5999ffbb51f1.png)

We should keep the first value (57) so `totalLineColor` can be changed when changing theme input `baseColor`.

- [ ] **Switch**: Theme input `fontColor` is not defined in the documentation. We should add it in the [themes page](https://developer.dxc.com/halstack/next/principles/themes/) with the token `labelFontColor`.

- [ ] **Table**: I would add an example in the Theme Builder and UX Config of the Resultset Table component.

- [ ] **Wizard**: In the documentation, move the token `selectedStepBorderColor` to the list of the theme input `baseColor`.
Besides, theme input `selectedFontColor` is not working because there is a typo in HalstackContext:
![image](https://user-images.githubusercontent.com/34685461/201922083-2767459b-a436-43e4-a3cf-081c064e42b0.png)

`SelectedStepFontColor` should not be using `fontColor` but `selectedFontColor`:
```wizardTokens.selectedStepFontColor = theme?.wizard?.selectedFontColor ?? wizardTokens.selectedStepFontColor;```

**Comment by Lisa159** [comment]
Components without default theme inputs:
- **Alert**: old component, it didn't have default theme inputs from the beginning.
- **App Layout**: new component, maybe default theme input for the hamburguer.
- **Bleed**: new component, no point of having default theme inputs as it is a layout.
- **Box**: old component, it didn't have default theme inputs from the beginning.
- **Bulleted List**: new component, maybe we could add default theme input for `fontColor`.
- **Card**: old component, it didn't have default theme inputs from the beginning.
- **Dialog**: old component, it didn't have default theme inputs from the beginning.
- **Flex**: new component, no point of having default theme inputs as it is a layout.
- **Heading**: old component, it didn't have default theme inputs from the beginning, maybe we could add one for `fontColor`.
- **Inset**: new component, no point of having default theme inputs as it is a layout.
- **Link**: old component. Font color can be changed with the prop `inheritColor`. However, we could add a default theme input `accentColor` like in the links of the quick nav component for the `hover` and `active` status.
- **Nav Tabs**: new component. Maybe as in the tabs, to add `baseColor`.
- **Paragraph**: new component, no point of having default theme inputs.
- **Quick Nav**: new component, explained in the comment above.
- **Tag**: old component. Maybe `fontColor` as default theme input.
- **Typography**: new component, no point of having default theme inputs.
