### ISSUE TITLE
DxcInput component does not support number type

### ISSUE THREAD

**Issue by mmascord** [dxc-technology/halstack-react#143]
The DxcInput component does not support type="number".  

It is strange that for masked input is necessary to use this property:  isMasked={true}.

I think it would be better if "isMasked={true}" was changed to type="password".

The DxcInput field should have the same property "type" as the standard HTML Input component and the Material-UI  TextField component.

Can you please add the "type" property with the following **standard** options:

```
<input type="button">
<input type="checkbox">
<input type="color">
<input type="date">
<input type="datetime-local">
<input type="email">
<input type="file">
<input type="hidden">
<input type="image">
<input type="month">
<input type="number">
<input type="password">
<input type="radio">
<input type="range">
<input type="reset">
<input type="search">
<input type="submit">
<input type="tel">
<input type="text">
<input type="time">
<input type="url">
<input type="week">
```

**Comment by jsardid** [comment]
I'm closing this one because is a duplicate of #104.
We have in our roadmap standardising data type formats in our design system, in order to guarantee consistency across different applications. 

We won't necessarily replicate html or material API, since we are implementing custom components .
For example, we already have a radio component, so there is no need of having an input type "radio".
