### ISSUE TITLE
Responsive dialog not being displayed correctly

### ISSUE THREAD

**Issue by aidamag** [dxc-technology/halstack-react#1485]
**Describe the bug**
Dialog in responsive mode is not been displayed correctly. In a certain width of the window (around 730px) the side margins are disappearing and the close button is getting cut.

**To Reproduce**
```
<DxcDialog overlay={true} isCloseVisible={true}>
  <DxcInset space="2rem">
    <DxcFlex direction="column" gap="1.5rem">
      <div>
        <h1>Sign in</h1>
      </div>
      <DxcFlex
        direction="column"
        gap="1.5rem"
      >
        <DxcTextInput label="Email" size="medium" clearable />
        <DxcPasswordInput label="Password" size="medium" clearable />
      </DxcFlex>
    </DxcFlex>
  </DxcInset>
</DxcDialog>
```

**Expected behaviour**
It should have a margin in both sides of the dialog.

**Screenshots**
Wrong:
![image](https://user-images.githubusercontent.com/34685461/220078056-7695f752-340b-4963-945d-600d00560223.png)

Correct:
![image](https://user-images.githubusercontent.com/34685461/220078123-89ce2935-e049-4b17-be3e-b775b418f0e4.png)

**Add labels**
Dialog.

**Comment by GomezIvann** [comment]
This is being caused by our endpoints and media queries. It seems we have a minimum width of 800px when the screen is bigger than 45rem (720px), which leads to that "cut" when the screen is resized between 720px and 800px. My suggestion is to change that minimum size to 696px, what do you think @rconcepcion3?

**Comment by rconcepcion3** [comment]
Hi @GomezIvann:

If I understand the fix correctly - if you adjust the minimum size to 696 - we won't have this issue for resolutions up to 800. If the resolution is below 696, the screen displays the small layout. 696 falls within our 'divisible by 8 approach'. If this fixes things, go for it... we just need to update the values in the Layout page (in the table and the images) - i will note this - possibly create a story in the backlog as well.

**Comment by GomezIvann** [comment]
The problem is that the `@media` query only applies when the screen is <= 45rem/720px (medium responsive size), until that size is reached, the minimum width is 800px, which is bigger than 720px (obviously), and results in the Dialog been cut off when, for example, the screen is 760px of width. That's the reason behind my proposal of changing the `min-width` to a value lower than 720px and, of course, divisible by 8.
I just wanted to ask you if you had any special value in mind @rconcepcion3 🚀.

**Comment by rconcepcion3** [comment]
Ok got it @GomezIvann. I don't have a better proposal for a different value. This is the window size just before the part where it gets cut for my screen (if I resize it any smaller):

![image](https://user-images.githubusercontent.com/101174179/221564944-b818647c-499c-4fce-b22d-22bc06246a93.png)

If 696px does the job... let's go for it then. No special value in mind for this as long as our base conditions are met (which they are).



This

**Comment by GomezIvann** [comment]
Perfect, I'll go for it!
