### ISSUE TITLE
Paginator component is different in user toolkit and designer toolkit

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#150]
As per CDK, the paginator component supports this:
 ![screen1](https://user-images.githubusercontent.com/72923647/105499602-be02fe00-5ce7-11eb-8798-e513b25e3a80.jpg)
 
However, for underwriter workbench our designer has designed it as below– he says it was there in the designer toolkit. 
Its not there in developers tool kit. 
![screen2](https://user-images.githubusercontent.com/72923647/105499615-c22f1b80-5ce7-11eb-8291-ea98984b5d60.jpg) 
 
Can you please provide a solution for this.

Missing Pieces: 'Go To Page" and 'Items per Page' should be configurable.

**Comment by DirkBaumannDXC** [comment]
Remark: Also for the Styler UI we need the described extension of the CDK paginator component ('Items per Page' and 'Go To Page").

**Comment by jsardid** [comment]
We have included the items per page select, and it's now available in the @next tag. We will include it in @latest soon.

Regarding the "go to page" select: After speaking with the design team, they are thinking about removing it from the guidelines. So we are not including it in the component in order to avoid future breaking changes.
