### ISSUE TITLE
Not able to pass a background color as a prop to the Card Component.

### ISSUE THREAD

**Issue by prajani4** [dxc-technology/halstack-react#1519]
We are not able to pass the background color as a prop to the Card component according to the design. So, we are unable to use the card component that we currently have.

We would like to have a feature to add background color to the card component accordingly.

As we are facing this issue with the existing card component we have built our custom code which is allowing us to add the background color.

**Comment by GomezIvann** [comment]
Hi @prajani4!

First, the definition of colours, sizes, and shapes... is an intrinsic part of a design system. Since these parameters are essential for guaranteeing accessibility and a good user experience, having the ability to change them, might go frontally against the intentions of the design system. That's why we do not offer props related to the styling features of the components. 

But, there are certain situations where it may be fair to change our design decisions. That's why we offer **themes**. Themes are custom-defined objects that allow users to override fundamental decisions of the Halstack Design System, as is your case.

Then, based on the number of decisions that can be overridden, Halstack Design System has two different theming strategies :
- Opinionated theme. This theming strategy lets you change some decisions of the design system but is still opinionated about the ones we consider fundamental. 
- Advanced theme. This theming strategy lets you change most of the design decisions of the design system (all the design tokens), trying to be as little opinionated as possible.

About your use case, the theming strategy to use is the **advanced theme**. If you go to the [specifications of the Card](https://developer.dxc.com/halstack/next/components/card/specifications/#design-tokens) component you would see its design tokens, which can be changed throw this advanced theming strategy.

![image](https://user-images.githubusercontent.com/44321109/225304044-f8feb771-be5d-441b-8e74-07dd6145fc2e.png)

As you can see, to change the `background-color` of the Card you need to change it in the Box component. So, with all this information, the final code example would be:

```
const advancedTheme = {
  box: {
    backgroundColor: "#fabada",
  },
};

const App = () => (
  <DxcApplicationLayout>
    <DxcApplicationLayout.Main>
      <HalstackProvider advancedTheme={advancedTheme}>
        <DxcInset space="5rem">
          <DxcCard>
            <DxcInset space="1.5rem">
              <DxcFlex direction="column" gap="0.5rem">
                <DxcHeading text="Title" level={3} />
                <DxcParagraph>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
                  maximus, metus ac iaculis lacinia, urna tellus efficitur
                  dolor, nec iaculis eros quam at ex.
                </DxcParagraph>
              </DxcFlex>
            </DxcInset>
          </DxcCard>
        </DxcInset>
      </HalstackProvider>
    </DxcApplicationLayout.Main>
  </DxcApplicationLayout>
);
```

![image](https://user-images.githubusercontent.com/44321109/225310534-7b930a09-f37f-4b3a-b8c4-5e49d584d888.png)


For more information, please, check this:
- The complete explanation of theming with examples of each possible strategy: https://developer.dxc.com/halstack/next/principles/themes/
- Advanced theme generator: https://developer.dxc.com/halstack/next/theme-generator/advanced-theme/

**Comment by prajani4** [comment]
Hello, The current DxcCard that we have is taking more space around the content inside the card. So, Is there any way to re-size the DxcCard according to the content we provide?

Please find the image below:

<img width="576" alt="card" src="https://user-images.githubusercontent.com/127923862/233342572-d5e92d54-c2c9-431b-945a-0e4a435d6e39.png">

**Comment by prajani4** [comment]
Hello @GomezIvann 

Can we have an update on the above concern?

**Comment by GomezIvann** [comment]
It has been some time since this issue was opened. Since no further comment has been made, we consider it answered and resolved. Thanks!
