### ISSUE TITLE
DxcChip - Icon alignment issue

### ISSUE THREAD

**Issue by HanojHanu** [dxc-technology/halstack-react#1536]
**Describe the bug**
only icon without any text, then icon position is not center.

**To Reproduce**
```jsx
// Icons
import { FaArrowRight, FaHistory } from "react-icons/fa";

// code ...
 <DxcChip
     prefixIcon={<FaHistory className="dxc-icon-size" />}
  />
```
Example:

2. Install the `@dxc-technology\halstack-react@9.0.0` dependencies and run the app.

**Screenshots**
![image](https://user-images.githubusercontent.com/53425981/228479594-a0a20e13-9df7-44b9-b123-7913cf7f90b9.png)

-------

**Expected behaviour**

**Additional context**
For example, If we add extra space then is it working..
```jsx
<DxcChip
    prefixIcon={<FaHistory className="dxc-icon-size" />}
    label=" "
  />
```
result
![image](https://user-images.githubusercontent.com/53425981/228480453-43532b28-a410-4ef0-b4d3-76fadb998998.png)

**Comment by GomezIvann** [comment]
Hello @HanojHanu!

The use case where you are getting that visual error (the icon-only `DxcChip`) is not valid. Chips are for filtering content, **they should always have a label**. That's why you are getting that visual defect, because that scenario is not covered by our component.

In this case, a `DxcButton` would be a better choice.

**Comment by GomezIvann** [comment]
As there has been no further activity, this issue is closed.
