### ISSUE TITLE
Jest Test - Issue

### ISSUE THREAD

**Issue by HanojHanu** [dxc-technology/halstack-react#1537]
**Describe the bug**
While Jest test case for reactjs, Error
``` pwd
 ReferenceError: ResizeObserver is not defined
```
**Screenshots**
![image](https://user-images.githubusercontent.com/53425981/228484393-c2ce1a79-ba88-4b32-93e9-ac2e55369d87.png)

**To Reproduce**
install  halstack-react v9
Run
``` cmd
npm run test:ci
```

**Additional context**
But, For me after adding this worked. Let hear for you that this approach is fine? `yes` or `no`

``` jsx

// Runs a function before any of the tests in this file run
beforeAll(() => {
   // something....
   
   // Worked - solution
  // ? ResizeObserver - added halstack-react v9
    global.ResizeObserver = class ResizeObserver {
      observe() {}
      unobserve() {}
      disconnect() {}
    };
    
    //....
}
```

**Comment by GomezIvann** [comment]
Hi @HanojHanu!

Yes, you are right, that's the solution to this problem. If you take a look at the tests of the components that use this API, they basically do the same. For example, [the Select's test file](https://github.com/dxc-technology/halstack-react/blob/84850c99fa12d8a2d3d65de8c821e9df3549a972/lib/src/select/Select.test.js). We are discussing how to address this issue, because Jest is the most common JS testing tool and we want to make the user experience as clean as possible!

Thanks for the feedback 🚀
