### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by mmascord** [dxc-technology/halstack-react#160]
When you select a word with the letter 'g' in it, the letter 'g' is cut.  This happens in the select component.

**Comment by jsardid** [comment]
@mmascord I've just tested in the documentation examples, and that is not happening to me.
![image](https://user-images.githubusercontent.com/7370399/108843533-1aa15380-75db-11eb-98dc-48689b214e46.png)

If the problem persists, can you please create a repository with that scenario in isolation so that we can try and reproduce it? 

Thanks!
