### ISSUE TITLE
Incorrect file name preview [File input component] in case of extra white spaces.

### ISSUE THREAD

**Issue by jvuppala01** [dxc-technology/halstack-react#2106]
**Describe the bug**
File name has multiple continuous white spaces between the words but file input preview combines multiple white spaces into single white space this causes confusion to the users.

**To Reproduce**
1. Create a new React app using Vite.
2. Install `@dxc-technology\halstack-react` package.
3. Keep a file name with multiple white spaces as ex: `20  LT           Product          Specs 1.pdf`
4. select this file using file input component 
5. It can be observed in file input preview `20 LT Product Specs 1.pdf` file name is displaying like this.
6. It can be observed clearly there is a mismatch between actual file name and preview in file input component.

**Expected behaviour**
Actual file name should be displayed without affecting due to white spaces.
**Screenshots**
![image](https://github.com/user-attachments/assets/4a70e57c-2246-448b-98d5-d13618016023)

![image](https://github.com/user-attachments/assets/8ea43219-9e14-4fae-9f5e-1c540bf9ef54)

**Additional context**

**Add labels**
file input

**Comment by GomezIvann** [comment]
Hello @jvuppala01!

Two things here:

1. You are correct, we are trimming the white spaces from the file names. We are going to fix this since it is not what we want.
2. It's generally not a good practice to have white spaces in file names, especially in technical or development contexts. While most modern systems can handle white spaces in file names, they can still cause issues in certain situations, such as:
   - Command-line operations: In terminal or script usage, spaces often need to be escaped or enclosed in quotes, which can be cumbersome and lead to errors.
   - URLs: Spaces in URLs are replaced with "%20," making the URL harder to read and manage.
   - Cross-platform compatibility: Some older systems or software may not handle spaces well, leading to potential problems when sharing files.

In any case, this is a fair request, and we will address it.

Thanks for the feedback!
