### ISSUE TITLE
Would like to have tabindex on elements, so that we can define our tabbing order sequence

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#216]
**Is your feature request related to a problem? Please describe.**
We would like to have tabindex attribute on elements, so that we can define our tabbing order sequence in our application.

**Describe the solution you'd like**
If all elements has tabindex attribute on elements, then we can give our tabbing order sequence.

Please let me know if anymore details are required.

**Comment by jsardid** [comment]
Thanks @ppurumala,

We will add tabIndex property to all the focusable components.

**Comment by sponnuswamydxc** [comment]
@jsardid Not just the tabindex. In addition to this, can you also consider the following while tabbing;

1. Tabbing is to be supported on toggles
2. Should secondary push buttons be skipped in tabbing order and only include primary ones?
3. Visual que showing the current location of the cursor (or selected field) 
4. Drop down when tabbed should open up the contents so that user can just key first letter of selection to see drop down selection

**Comment by jsardid** [comment]
Thanks Senthil,

We are working on 1 and 4 already.
Regarding 2, secondary buttons also need to be accessible with the keyboard.
Regarding 3, that should be happening already. If it's not happening with a particular component, please open an independent issue.

**Comment by jsardid** [comment]
tabIndex attribute is added for interactive components in 3.2.0

**Comment by sponnuswamydxc** [comment]
Thanks @jsardid we will check this
