### ISSUE TITLE
DXCDate - Not self manage invalid 

### ISSUE THREAD

**Issue by NorbertPointu** [dxc-technology/halstack-react#236]
**Describe the bug**
You can enter any char, not only integer.
Invalid property is not set when the user input is not match the given format

**To Reproduce**
1. Create a new React App using `create-react-app`
2. Install the `@dxc-technology\halstack-react` dependencies and run the app
3. use DXCDate, with format "MM-dd-yyyy"
4. don't handle invalid prop
5. set an invalid date format as "01-**6**1-1995"
6. The input will be not invalid (no red)
 

**Expected behavior**
Invalid has to be managed with the component itself, not outside with the second param of onChange and invalid prop.

**Screenshots**
![image](https://user-images.githubusercontent.com/62135994/115531010-9561b480-a294-11eb-9d8a-36192d201c32.png)

**Additional context**

**Add labels**
React HalStack V3

**Comment by jsardid** [comment]
Currently:
- The DxcDate component already takes the responsibility of validating the input value against the given date format. If it's a valid date, a "dateValue" property is passed to the handler as a parameter (otherwise, this attribute is null).
- The DxcDate component does NOT take the responsibility of deciding when the field is visually shown as invalid. It is controlled by the parent component.

This delegation of responsibility is intentional, for the sake of flexibility. This way, you can display the field as valid/invalid for any other reason and not only because of formatting errors (for example, someone might decide that some date range is invalid).
