### ISSUE TITLE
DxcDate - Date icon not operational

### ISSUE THREAD

**Issue by NorbertPointu** [dxc-technology/halstack-react#238]
**Describe the bug**
When we click on icon to display the calendar, nothing happens
We have copy/paste the exemple code from CDK documentation

**To Reproduce**
1. Create a new React App using `create-react-app`
2. Install the `@dxc-technology\halstack-react` dependencies and run the app
3. Copy/paste the exemple code from CDK documentation into a DXCBox
4. Click on calendar icon
5. Nothing appears.

**Expected behavior**
Have the calendar displayed and to be able to select a date ** 

**Screenshots**
![image](https://user-images.githubusercontent.com/62135994/115534481-1e2e1f80-a298-11eb-83f6-86955cae0dbe.png)

**Additional context**

**Add labels**
React HasStack V3

**Comment by jsardid** [comment]
Hello @NorbertPointu 

We are not able to reproduce the issue. Actually it does work in the documentation site (https://developer.dxc.com/tools/react/3/#/components/date)

Maybe there is some compatibility issue with one of the libraries you are using.
Could you please create a repository with the minimum amount of code so that we can reproduce it?

Thanks!

**Comment by NorbertPointu** [comment]
I'm trying to reproduce the error in a new project. For now, i don't success. I will continue and come back to you
