### ISSUE TITLE
Add ref property to input components

### ISSUE THREAD

**Issue by NorbertPointu** [dxc-technology/halstack-react#241]
**Is your feature request related to a problem? Please describe.**
We want to manage uncontrolled input in our application.  
It seems the definition of uncontrolled input is different from the CDK and REACT : 
https://reactjs.org/docs/uncontrolled-components.html

For example, the uncontrolled CDK exemples for DXCTextField is based on onChange :
![image](https://user-images.githubusercontent.com/62135994/115537520-2f2c6000-a29b-11eb-8180-8f8e083ea620.png)

On each key press, onChange is trigged. In fact, this is a controlled component.
Controlled input component makes component re-render on each key press and can cause **performance issue**.

**Describe the solution you'd like**
We would like to set a *ref* to each CDK components.
The priority will be on Input component used in Form.
We want to use yup validation form.

**Describe alternatives you've considered**

**Additional context**

**Add Labels**
React HalStack V3

**Comment by jsardid** [comment]
A couple of clarifications:
- The example you shared doesn't trigger a re-render, and even if it did, in the vast majority of cases it wouldn't cause a performance issue. 
- If you choose not use controlled components, the reason shouldn't be this type of micro-optimization.

Our components are uncontrolled, because you don't need to pass a value for them to work. But I agree it would be nice to have the ability of setting a ref to the input, in order to facilitate the access to the value. We will incorporate this functionality.

**Comment by jsardid** [comment]
The new input components took feedback from this issue and they already provide the ref property.
These components are already available in the @next release (https://developer.dxc.com/tools/react/3/#/components/newInputText) and will be part of 4.0.0 once we release it during the next couple of weeks.

Thanks for the feedback @NorbertPointu 😀
