### ISSUE TITLE
DXC_Button : Warning when we use the mode flat

### ISSUE THREAD

**Issue by NorbertPointu** [dxc-technology/halstack-react#263]
**Describe the bug**

As the Icon button doesn't exist, we found a way to have smaller button as the exemple of the Resultset Table : 

![image](https://user-images.githubusercontent.com/62135994/116511980-9794c600-a8c7-11eb-84b1-a883ed9de74e.png)

But, we have warning when we use this mode.

![image](https://user-images.githubusercontent.com/62135994/116512140-d9257100-a8c7-11eb-8ca2-3b9cfb3785aa.png)

**Comment by jsardid** [comment]
@NorbertPointu the documentation of the button (in line with the design guidelines) states that the button has only three modes (primary, secondary and text). Which is exactly the warning you are getting. Please use one of those three.

I have just realised that when you pass a mode out of those three, some sort of hybrid is rendered. That's a bug and we'll fix it so that if you pass an invalid mode, it renders the default mode (primary).

**Comment by jsardid** [comment]
Just created #264 for the issue I was mentioning.

Closing this one, since the warning message is actually fine.
