### ISSUE TITLE
[Table] ScrollBar tokens

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#315]
The example doesn't show a scrollbar so it's impossible to check the changes on the `scrollBarThumbColor` and `scrollBarTrackColor` tokens

**Comment by GomezIvann** [comment]
I didn't put a preview with scroll because, right now it is impossible to force due to its implementation. Tables can't have their own scroll, you achieve this by wrapping them into a div container with `overflow-y: auto` and a _fixed height_ (for the vertical scroll). So, should i add a fixed height so that when it's reached the scroll is shown? In that case, which value should it have?
