### ISSUE TITLE
[Dialog] Content with scroll overlap

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#320]
**Describe the bug**
When the content causes the scroll to show up, it applies to the whole dialog, instead to only the content, as the guidelines say. This leads to an overlap with the close action. Right now it displays like this:

![image](https://user-images.githubusercontent.com/44321109/119630906-ac557280-be0f-11eb-8f5e-d4541d466f01.png)

This is how it should look like according to the guidelines:

![image](https://user-images.githubusercontent.com/44321109/119631281-05250b00-be10-11eb-8223-5357228d3adf.png)

**Comment by marcialfps** [comment]
I think @aweell can give us a lot of guidance on this issue as it is very much related to the guidelines. In this case I detect two problems:

- The positioning of the close button is not correct and it is not the size indicated in the design guidelines. Even so, the size of 20x20 pixels indicated makes the button look very small.
- The component does not control the content it receives, so the title is included in the scroll area.

I think we should review this component in depth.

**Comment by aweell** [comment]
I'll review it.

@marcialfps maybe we should contemplate having a title area predefined in the component so it's outside of the custom content area and never scrolls?

https://github.com/dxc-technology/halstack-style-guide/issues/238#issue-910200202

**Comment by GomezIvann** [comment]
Regarding this issue, i think we have to reach an agreement. I understand what you say @aweell but by doing so, don't you think we lose flexibilty? since beforehand, we can't predict what is inside the Dialog component and which parts of that content are going to be scrollable. I think that decision has to be made by the user itself, not by us.
I agree maybe it is interesting to give a predefined dialog, but also to give the freedom to put inside whatever the user wants.

**Comment by aweell** [comment]
By having predefined sections on a dialog the user can always decide which ones to use, if I don't want to have a `header` I can remove that section and use only `content` and `footer` or even only `content`.

The [current guidelines](https://developer.dxc.com/design/guidelines/components/dialog) are actually exploring the idea of having this approach:

![Captura de pantalla 2021-06-03 a las 11 33 41](https://user-images.githubusercontent.com/44420072/120623027-a25eef80-c45f-11eb-9319-eb05b204b161.png)

Right now we're providing a lot of flexibility so users can always change the `padding-top` or the overall `padding` to avoid the scroll and the close button overlap.

We can open a different discussion about if a dialog should be used for an amount of content that is going to produce overflow instead of just putting this content on a page.

![Captura de pantalla 2021-06-03 a las 11 43 50](https://user-images.githubusercontent.com/44420072/120624455-0504bb00-c461-11eb-87a4-35c4ac9686dc.png)

_Image extracted from the article: [Modal vs Page: A Decision Making Framework](https://uxplanet.org/modal-vs-page-a-decision-making-framework-34453e911129) by Ryan Neufeld_

My conclusion here is that reviewing the component now will lead to some structural changes that will affect the current properties. The guidelines can be updated eluding the example of scrollable content since is something the user should avoid.

**Comment by aweell** [comment]
Closed via https://github.com/dxc-technology/halstack-style-guide/issues/238

@marcialfps the icon to be used for the close button:

https://fonts.gstatic.com/s/i/materialiconsoutlined/close/v15/24px.svg
