### ISSUE TITLE
Link with action doesn't have a visited state

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#326]
The Link component, when it has an `onClick` prop, becomes a button (not aesthetically, but in code). Is this right? In that case, shouldn't it have a visited state as the regular link?

![image](https://user-images.githubusercontent.com/44321109/119987444-53c7d600-bfc5-11eb-8e89-fbf39575cc5c.png)

**Comment by aweell** [comment]
Shouldn't be `the link with action` categorized as a `button` instead of a `link`?

![Captura de pantalla 2021-05-28 a las 15 47 27](https://user-images.githubusercontent.com/44420072/119993596-07cc5f80-bfcc-11eb-97cf-22e402600e8d.png)

From my understanding `:visited` pseudo-class can only be applied to links right?

**Comment by jsardid** [comment]
I agree @aweell, you cannot visit an action.
As you are saying, this might be considered a button although we are rendering it as a link. We will have this into consideration when reviewing the link component which is already a roadmap task.
