### ISSUE TITLE
Text is not showed in Header

### ISSUE THREAD

**Issue by marcialfps** [dxc-technology/halstack-react#439]
**Describe the bug**
If you introduce a text component like `p` or `h1` the text is not showed.

**To Reproduce**
1. Use DxcHeader.
2. Set in content prop: `<h1>hello</h1>`
5. See error

**Expected behavior**
Text should be showed.

**Screenshots**
![image](https://user-images.githubusercontent.com/35959222/143275543-79a95ba0-2804-4f70-890b-a2d8649e497a.png)

**Add labels**
DxcHeader, 3.4.1

**Comment by jsardid** [comment]
@aweell I think the proper fix to this will only come once we have the text component in place. This text component will automatically render the contrast based on the lightness of the header background.

In the meantime, since the user can pass custom (non-halstack) text as content, I see three possible provisional solutions:
- Hardcode the "color" CSS property associated to the header content to black, which might make more sense as a default.
- Add contentColor and contentColorOnDark theme tokens that will apply to the custom (non-halstack) components used inside the header.
- Let the user style the content manually.

Do you have a preference?

**Comment by jsardid** [comment]
We will add contentColor and contentColorOnDark theme tokens that will apply to the custom (non-halstack) components used inside the header.
