### ISSUE TITLE
[Number Input] Mouse wheel modifies the value of the component

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#460]
Number Input component modifies its value when the cursor is over it and the mouse wheel scrolls. This is inherited from the native `<input type="number" />` and Reacts own implementation of the `wheel` event. The solution would be to remove the default behaviour in future iterations of the component.

**Comment by marcialfps** [comment]
I have found a single number input that controls this functionality by default and provides a prop to enable or disable this functionality. This is [Chakra Number Input](https://chakra-ui.com/docs/components/form/number-input#numberinput-props) and the prop is `allowMouseWheel`. They can control this functionality because internally the type of input they use is text.

For the rest of the other design systems I have reviewed, they keep this default functionality and use a native input number except for [Spectrum](https://react-spectrum.adobe.com/react-spectrum/NumberField.html#props) which uses the text type.

I think we should keep the default functionality if we want to continue using a native input number.

### References

- [Next UI](https://nextui.org/docs/components/input#input-types)
- [Gestalt](https://gestalt.netlify.app/numberfield)
- [Spectrum](https://react-spectrum.adobe.com/react-spectrum/NumberField.html#props)
- [Chakra](https://chakra-ui.com/docs/components/form/number-input#numberinput-props)

**Comment by GomezIvann** [comment]
We need to figure out a way of stopping the page scroll when the focus is on the number input and the cursor is hovering over the component. Under these conditions, the value of the number input should be increased or decreased with the mouse wheel.
