### ISSUE TITLE
Review Tabs implementation for client side navigation

### ISSUE THREAD

**Issue by jsardid** [dxc-technology/halstack-react#823]

**Comment by marcialfps** [comment]
Discussion: #878

**Comment by marcialfps** [comment]
# TabNav proposal

## Use cases

- When a Tab is clicked, a new page opens, changing the browser URL.
- A Tab can be disabled, ignoring any action.
- Control when the user clicks on any of the Tabs. Example: an unregistered user cannot access the Tabs. *
- Support client-side navigation (React Router or NextJS Link).
- Indicate the active Tab without the need to control the Tab change (uncontrolled case).
- Indicate the active Tab and control the Tab change (controlled case).
- Add an icon to a tab.
- Indicate the tabIndex attribute of the active Tab.
- One of the Tabs can be controlled with onClick.

## Props

### DxcTabNav
| Prop  | Type | Default value | Description |
| ------------- | ------------- | ------------- | ------------- |
| defaultActiveTab  | integer  | 0 | Active tab for uncontrolled mode. |
| activeTab | integer | | Active tab for controlled mode. |
| iconPosition | 'top' or 'left' | 'top' | Icon position. |
| onTabClick* | function | | Called when the user clicks on Tab. This function will receive the index of the clicked Tab. It can't be combined with Tabs that use href.  |
| margin | string or object | | Margin of the TabNav. |

### DxcTab
| Prop  | Type | Default value | Description |
| ------------- | ------------- | ------------- | ------------- |
| href | string | | Href of the rendered anchor. |
| onClick | function | | Called when the user clicks the Tab. |
| icon | node or string | | Icon placed in the Tab. |
| disabled | boolean | false | Indicates if the Tab is disabled or not. |
| children | node or string | | If it is a string the component is rendered as an anchor. Otherwise, the content will be considered as a custom Tab. |

## Example

```
<DxcTabsNav
  onTabClick={(index) => {
    return index - 1;
  }}
  activeTab={1}
  tabIndex={3}
  iconPosition="top"
>
  <DxcTab href="#" icon={MySVGIcon}>
    My anchor Tab with icon
  </DxcTab>
  <DxcTab onClick={() => {}}>
    My active and controlled Tab
  </DxcTab>
  <DxcTab href="#" disabled>
    My disabled Tab
  </DxcTab>
  <DxcTab>
    <NextLink href="#">
      <a>My custom Tab</a>
    </NextLink>
  </DxcTab>
</DxcTabsNav>
```


*Waiting for discussion.
